---
- hosts: localhost
  become: yes
  become_method: sudo
  tasks:
  - name: Remove Docker service
    apt:
      pkg: "{{ item }}"
      state: absent
    loop:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
  - name: Update 
    apt:
      update_cache: yes
  - name: Install Pre-requisite
    apt:
      pkg: "{{ item }}"
      state: present
    loop:
      - ca-certificates
      - curl
      - gnupg
  - name: Create folder for docker gpgkey
    file:
      path: /etc/apt/keyrings
      mode: 0755
  - name: Download Docker Gpg key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg 
  - name: Setup the repository
    shell: echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - name: Updated permisson to docker.gpg
    file:
      path: /etc/apt/keyrings/docker.gpg
      mode: a+r
  - name: Update
    apt:
      update_cache: yes
  - name: Install docker
    apt:
      pkg: "{{ item }}"
      state: present
    loop:
      - docker-ce
      - docker-ce-cli
    
    